version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
  qdrant:
    image: docker.io/qdrant/qdrant:v1.11.5
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant:/qdrant/storage
volumes:
  mongo-data:
  mongo-config:
  qdrant:
